FROM python:3.10-slim

WORKDIR /app

# Copy the shared directory and setup.py
COPY shared ./shared
COPY setup.py ./

# Copy only the data_preprocessing service files
COPY document_analysis ./document_analysis

# Install dependencies
RUN pip install --no-cache-dir .

EXPOSE 9000

CMD ["python", "document_analysis/api.py"]
