FROM python:3.10-slim

WORKDIR /app

# Copy the shared directory and setup.py
COPY shared ./shared
COPY setup.py ./

# Copy only the data_preprocessing service files
COPY data_preprocessing ./data_preprocessing

# Install dependencies
RUN pip install --no-cache-dir .

# Expose port 9001
EXPOSE 9001

CMD ["python", "data_preprocessing/api.py"]
