FROM python:3.10-slim

WORKDIR /app

# Copy the shared directory and setup.py
COPY shared ./shared
COPY setup.py ./

# Copy only the data_preprocessing service files
COPY face_analysis ./face_analysis

# Install dependencies
RUN pip install --no-cache-dir .
RUN apt-get update && apt-get install -y libglib2.0-0 ffmpeg libsm6 libxext6

# Expose port 9001
EXPOSE 9005

CMD ["python", "face_analysis/api.py"]
