version: '3.9'

services:
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "${KAFKA_PORT}:9092"
    networks:
      - spanda
    profiles: ["data-connectors"]

  nifi:
    image: apache/nifi:latest
    ports:
      - "8082:8080"
    networks:
      - spanda
    profiles: ["data-connectors"]

  airflow:
    image: apache/airflow:latest
    ports:
      - "${AIRFLOW_PORT}:8080"
    networks:
      - spanda
    profiles: ["aiops"]

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./aiops/prometheus/config:/etc/prometheus
    ports:
      - "${PROMETHEUS_PORT}:9090"
    networks:
      - spanda
    profiles: ["aiops"]

  grafana:
    image: grafana/grafana
    ports:
      - "${GRAFANA_PORT}:3000"
    networks:
      - spanda
    profiles: ["aiops"]

networks:
  spanda:

