FROM python:3.10-slim

WORKDIR /edtech

# Copy files
COPY . /edtech

RUN apt-get update && apt-get install -y poppler-utils gcc libpq-dev && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip && pip install -e FunctionalBlocks/BusinessLogic

EXPOSE 9002

CMD ["uvicorn", "FunctionalBlocks.BusinessLogic.api:app", "--host", "0.0.0.0", "--port", "9002", "--reload"]
