version: "3.8"

services:
  frontend:
    image: hanish1/afe-frontend:latest
    container_name: afe-frontend-dev
    ports:
      - "${FRONTEND_PORT}:80"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    restart: unless-stopped
    networks:
      - dev-network

networks:
  dev-network:
    external: true