services:
    # Spark
  spark:
    platform: linux/x86_64
    image: alexmerced/spark35nb:latest
    ports: 
      # - 8080:8080  # Master Web UI
      - 7077:7077  # Master Port
      - 8888:8888  # Notebook
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=admin #minio username
      - AWS_SECRET_ACCESS_KEY=password #minio password
    container_name: spark
    networks:
      - Spanda-Net
    volumes:
      - ./:/workspace/user_data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    networks:
      - Spanda-Net
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    container_name: kafka
    networks:
      - Spanda-Net
    volumes:
      - ./:/user_data
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      # Defines the interface and port Kafka listens on
      # Replication factor for the offsets topic
      # KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  nifi:
    image: apache/nifi:latest
    container_name: nifi
    ports:
      - "8080:8080"  
      - "8443:8443"  


    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - SINGLE_USER_CREDENTIALS_USERNAME=admin 
      - SINGLE_USER_CREDENTIALS_PASSWORD=password1234
    volumes:
      - ./:/user_data
    # networks:
    #   de-end-to-end:
    networks:
      - Spanda-Net
  
networks:
  Spanda-Net:
    external: true
    name: Spanda-Net
    driver: bridge
    



