version: '3.9'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - platform_network
      - app_network
networks:
  platform_network:
    external: true
  app_network:
    external: true
