version: '3.9'
services:
  ollama:
    image: ollama/ollama
    container_name: ollama-platform-gpu
    ports:
      - "11434:11434"
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
      - ollama:/root/.ollama
    networks:
      - platform_network
      - app_network
      - dev-network
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              count: all
              capabilities: [gpu]
    restart: unless-stopped
volumes:
  ollama:
    driver: local
networks:
  platform_network:
    external: true
  app_network:
    external: true
  dev-network:
    external: true