services:
  # Nessie Catalog Server Using In-Memory Store
  nessie:
    image: projectnessie/nessie:latest
    container_name: nessie
    networks:
      - Spanda-Net
    ports:
      - ${NESSIE_EXTERNAL_PORT}:19120

  # Minio Storage Server
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_DOMAIN=${MINIO_DOMAIN}
      - MINIO_REGION_NAME=${MINIO_REGION_NAME}
      - MINIO_REGION=${MINIO_REGION}
    networks:
      - Spanda-Net
    ports:
      - ${MINIO_EXTERNAL_PORT_1}:9001
      - ${MINIO_EXTERNAL_PORT_2}:9000

    command: ["server", "/data", "--console-address", ":9001"]
  
networks:
  Spanda-Net:
    external: true
    name: Spanda-Net
    driver: bridge
    