---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weaviate-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: verba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: verba
  template:
    metadata:
      labels:
        app: verba
    spec:
      containers:
      - name: verba
        image: prabhas264/verba:latest
        ports:
        - containerPort: 8000
        env:
        - name: WEAVIATE_URL_VERBA
          value: "http://weaviate:8080"
        - name: OLLAMA_URL
          value: "http://ollama:11434"
        - name: OLLAMA_MODEL
          value: "llama3.3"
        - name: OLLAMA_EMBED_MODEL
          value: "bge-large:latest"
        volumeMounts:
        - name: data
          mountPath: /data
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 5
      volumes:
      - name: data
        emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weaviate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weaviate
  template:
    metadata:
      labels:
        app: weaviate
    spec:
      containers:
      - name: weaviate
        image: semitechnologies/weaviate:1.25.10
        ports:
        - containerPort: 8080
        args:
        - --host
        - 0.0.0.0
        - --port
        - "8080"
        - --scheme
        - http
        env:
        - name: OPENAI_APIKEY
          value: ${OPENAI_API_KEY}
        - name: COHERE_APIKEY
          value: ${COHERE_API_KEY}
        - name: QUERY_DEFAULTS_LIMIT
          value: "25"
        - name: AUTHENTICATION_ANONYMOUS_ACCESSver_ENABLED
          value: "true"
        - name: PERSISTENCE_DATA_PATH
          value: "/var/lib/weaviate"
        - name: ENABLE_MODULES
          value: "e"
        - name: CLUSTER_HOSTNAME
          value: "node1"
        volumeMounts:
        - name: weaviate-storage
          mountPath: /var/lib/weaviate
        livenessProbe:
          httpGet:
            path: /v1/.well-known/ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 5
      volumes:
      - name: weaviate-storage
        persistentVolumeClaim:
          claimName: weaviate-data
---
apiVersion: v1
kind: Service
metadata:
  name: verba
spec:
  selector:
    app: verba
  ports:
  - port: 8000
    targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: weaviate
spec:
  selector:
    app: weaviate
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: grpc
    port: 50051
    targetPort: 50051