version: "3.9"

services:
  vllm:
    image: vllm/vllm-openai:latest
    runtime: nvidia
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
    ports:
      - "8000:8000"
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    command: [
      "--host", "0.0.0.0",
      "--port", "8000",
      "--model", "joshmiller656/Llama3.2-3B-Instruct-AWQ-INT4",
      "--tokenizer", "joshmiller656/Llama3.2-3B-Instruct-AWQ-INT4",
      "--dtype", "auto",
      "--max-model-len", "4000",
      "--max-num-batched-tokens", "8000",
      "--max-num-seqs", "256",
      "--gpu-memory-utilization", "0.90",
      "--tensor-parallel-size", "1",
      "--trust-remote-code",
      "--enforce-eager",
      "--enable-server-load-tracking",
      "--load-format", "auto" # Can add as many/as little arguments as we want, this is dependent on what the user wants
    ]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s