services:
  dremio:
    platform: linux/x86_64
    image: dremio/dremio-oss:latest
    ports:
      - ${DREMIO_WEB_UI_EXTERNAL_PORT}:9047 #Dremio Web UI 
      - ${DREMIO_JDBC_CLIENT_EXTERNAL_PORT}:31010 #ODBC/JDBC Client Port 
      - ${DREMIO_FLIGHT_SQL_EXTERNAL_PORT}:32010 #Flight SQL Port
    container_name: dremio
    networks:
      - Spanda-Net

networks:
  Spanda-Net:
    external: true
    name: Spanda-Net
    driver: bridge
    